[platformio]
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
build_flags =
    -DUSER_SETUP_LOADED
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_GFXFF
    -DSPI_FREQUENCY=27000000
    -DSPI_READ_FREQUENCY=20000000
    -Wl,--wrap=mbedtls_platform_entropy_poll
